In [1]:
import numpy as np

In [14]:
N=4

A = np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [0,0,0,1]])
B = np.array([[2,3,4,5],
              [0,2,0,0],
              [0,0,2,0],
              [0,0,0,2]])

B

array([[2, 3, 4, 5],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])

In [26]:
def matrix_multiplication(A,B):

    N = A.shape[0]
    out = np.zeros((N,N))

    A00 = A[0:N//2,0:N//2]
    A01 = A[0:N//2,N//2:]
    A10 = A[N//2:,0:N//2]
    A11 = A[N//2:,N//2:]

    B00 = B[0:N//2,0:N//2]
    B01 = B[0:N//2,N//2:]
    B10 = B[N//2:,0:N//2]
    B11 = B[N//2:,N//2:]
    
    if N==2:
        out[0,0] = A00*B00+A01*B10
        out[0,1] = A00*B01+A01*B11
        out[1,0] = A10*B00+A11*B10
        out[1,1] = A10*B01+A11*B11        
        return out
    else:
        P1 = matrix_multiplication(A00,B00)
        P2 = matrix_multiplication(A01,B10)
        P3 = matrix_multiplication(A00,B01)
        P4 = matrix_multiplication(A01,B11)
        P5 = matrix_multiplication(A10,B00)
        P6 = matrix_multiplication(A11,B10)
        P7 = matrix_multiplication(A10,B01)
        P8 = matrix_multiplication(A11,B11)
        out[0:N//2,0:N//2] = P1+P2
        out[0:N//2,N//2:] = P3+P4
        out[N//2:,0:N//2] = P5+P6
        out[N//2:,N//2:] = P7+P8
        return out

In [27]:
matrix_multiplication(A,B)

array([[2., 3., 4., 5.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [28]:
def subcubic_matrix_multiplication(A,B):

    N = A.shape[0]
    out = np.zeros((N,N))

    A00 = A[0:N//2,0:N//2]
    A01 = A[0:N//2,N//2:]
    A10 = A[N//2:,0:N//2]
    A11 = A[N//2:,N//2:]

    B00 = B[0:N//2,0:N//2]
    B01 = B[0:N//2,N//2:]
    B10 = B[N//2:,0:N//2]
    B11 = B[N//2:,N//2:]
    
    if N==2:
        out[0,0] = A00*B00+A01*B10
        out[0,1] = A00*B01+A01*B11
        out[1,0] = A10*B00+A11*B10
        out[1,1] = A10*B01+A11*B11        
        return out
    else:
        P1 = matrix_multiplication(A00,B01-B11)
        P2 = matrix_multiplication(A00+A01,B11)
        P3 = matrix_multiplication(A10+A11,B00)
        P4 = matrix_multiplication(A11,B10-B00)
        P5 = matrix_multiplication(A00+A11,B00+B11)
        P6 = matrix_multiplication(A01-A11,B10+B11)
        P7 = matrix_multiplication(A00-A10,B00+B01)
        out[0:N//2,0:N//2] = P5+P4-P2+P6
        out[0:N//2,N//2:] = P1+P2
        out[N//2:,0:N//2] = P3+P4
        out[N//2:,N//2:] = P1+P5-P3-P7
        return out

In [29]:
subcubic_matrix_multiplication(A,B)

array([[2., 3., 4., 5.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])